### ISSUE TITLE
Galerie: Produktbilder / eigenes Template

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#10]
Auch auf die Gefahr hin zu nerven... Ich habe hier etwas, was vor der 1.7.2 nicht so war:

Ich lasse auf den Produktseiten Bilder zum entsprechenden Produkt anzeigen. Im Produkttemplate rufe ich diese so auf:

{PRODUCT_GALLERYPICS(ID,7,0,0,"meintemplate")}

Und hier gibt es jetzt ein Problem mit eigenen Templates, im obigen Beispiel "meintemplate". Unabhängig von den anderen Angaben, unabhängig vom Template-Name und unabhängig vom Inhalt des Templates spuckt mir die Seite direkt am Anfang des Templates ein "ï»¿" aus. Selbst bei einem komplett leeren Template bekomme ich dies angezeigt.

Einzig wenn ich hier kein eigenes Template angebe und somit auf die productpic.html als Standardtemplate zurückgegriffen wird, erfolgt die Ausgabe korrekt.

**Comment by Michael-Moedersheim** [comment]
Sie wissen aber schon dass man Dateien auch in einem gewissen Zeichenformat abspeichern kann?

**Comment by bigfraggle** [comment]
Danke, guter Hinweis.
Hatte ausnahmsweise mal einen anderen Editor verwendet.

**Comment by scheb** [comment]
Das was als "ï»¿" sichtbar wird, ist der sogenannte "BOM tag", der zu Beginn eines Textfiles stehen kann, um die Zeichencodierung der Datei zu signalisieren. Template-Dateien am besten immer ohne BOM tag abspeichern.

http://stackoverflow.com/tags/byte-order-mark/info

**Comment by bigfraggle** [comment]
Man lernt nicht aus. Hatte nach der Zeichenfolge durchaus gesucht, aber irgendwie nichts gefunden...
