### ISSUE TITLE
{AFFILIATE.URL} funktioniert nicht (mehr?)

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#12]
Hi,

ist mir gerade aufgefallen:

{AFFILIATE.URL} gibt die URL nicht (mehr?) aus.

Grüße
Marc

**Comment by bigfraggle** [comment]
Update: Passiert nur bei der Sortierauswahl "Zufällige Reihenfolge"

**Comment by DOHRMANN-SOFTWARE** [comment]
Bei mir passiert der Fehler nicht.
