### ISSUE TITLE
Variabeln des Moduls 'Kommentarfunktion' überschreibt andere Variabeln

### ISSUE THREAD

**Issue by DOHRMANN-SOFTWARE** [scheb/open-apexx#15]
Ich habe jeweils für die Module 'News', 'Artikel', 'Download' und 'Kommentarfunktion' in der Datei 'public_byuser.php' in den Gruppen 'news', 'articles', 'detail' und 'comments' eine Variabel mit der selben Bezeichnung erstellt.
Aber bei der Ausgabe wird immer dem Modul 'Kommentarfunktion' den Vorzug gegeben.
Wenn ich das Modul 'Kommentarfunktion' deaktiviere, hat jeder Bereich der die Variabel nutzt den richtigen Inhalt.

Gibt es eine spezielle Reihenfolgen wie die Sprachvariabelen genutzt werden?
Denn so wird das modulare System zerstört.

**Comment by scheb** [comment]
Wenn man ein voll-modulares System möchte, würde man normalerweise Namespaces verwenden und alle Variablen mit einem Prefix versehen (welches z.B. dem Modulnamen entspricht). apexx verzichtet auf Präfixe, um es einfach zu halten und die Lesbarkeit zu verbessern. Das hat natürlich den Nachteil, dass Variablen sich überschreiben können, wenn sie gleich benannt sind. Die Lösung dafür ist ganz einfach dafür zur sorgen, dass die gewählten Variablennamen möglichst einzigartig sind.

Generell zur Reihenfolge - das kann ich so sicher auch nicht mehr sagen - ich glaube Variablen der Seite selbst werden zuerst geladen und zusätzliche Module im Anschluss. Daher überschreiben die Variablen der Kommentarfunktion bestehende Variablen, die bereits geladen wurden.

**Comment by DOHRMANN-SOFTWARE** [comment]
Was ist so schlimme an Präfix.
Ich würde das gerne umsetzten.
Da jedes Modul seine eigen Spachdatei hat, wäre es ja kein Problem es umzusetzen.
Und die Lesbarkeit, würde ich sagen, wird weder verschlimmert noch unbeding verbessert, aber die Zuordnung und das Problem des überschreibens würde verbessert werden.

**Comment by scheb** [comment]
Oke, gut, sagen wir alle Sprachvariablen werden mit der jeweiligen Modul-ID gepräfixt, also aus "VARIABLE" wird dann z.B. "NEWS.VARIABLE".

Wie stellst die Abwärtskompatibilität sicher? Oder sollen dann alle Nutzer die auf diese zukünftige Version updaten dann durch alle ihre Templates gehen und die Präfixe an die Sprachvariablen anhängen?

**Comment by DOHRMANN-SOFTWARE** [comment]
Egal was man macht, die Abwärtskompatibilität wird immer ein Problem bleiben.
Das Produkte-Modul habe ich mit Kategorien und Datenfelder erweitert.
Die Daten werden ja durch die von dir geschriebenen Funktionen angepasst, aber die Templates müssen angepasst werden.
Die Variabeln kann man ja einfach mit Suchen & Ersetzen von Notepad++ oder einem anderen Programm in den Templates anpassen.
Aber das ist besser, als wenn sich die Variabeln überschreiben.
Vorallem wenn man bedenkt, das auch noch weitere Module dazukommen könnten.
Es ist ja auch nicht toll, wenn auf einer Seite mehrere Module nutzt, und dann steht an einer Stelle der falsche inhalt.
Wenn man ein Programm weiter entwickelt, wird die Abwärtskompatibilität immer ein Problem bleiben, sonst kann man sich nur auf die Fehlerbeseitigung beschränken.

**Comment by scheb** [comment]
Abwärtskompatibilität ist immer ein Problem, kein Zweifel. Ich würde sogar behaupten das ist das größte Problem wenn man Software nicht nur "für sich" entwickelt. Jeder Bruch der Abwärtskompatibilität sorgt dafür, dass die Nutzer Migrationsarbeiten ausführen müssen, um auf die neue Version zu aktualisieren und das verhindert halt oft, dass die Leute überhaupt aktualisieren werden.

Es gibt verschiedene Strategien wie man damit umgehen kann. 

1) Man kann einfach sagen "sollen die Nutzer halt die Migration machen" und nimmt damit in Kauf, dass man diese Nutzer verlieren wird, weil sie eben nicht bereit sind die Arbeit zu investieren für das Upgrade. Insbesondere dann wenn der Mehrwert des Upgrades nicht groß genug ist.
2) Man kann zweigleisig fahren, eine Version mit der alten Funktionalität anbieten und eine mit der neuen Funktionalität. Da es sich um einen Bruch der Abwärtskompatibilität handelt würde das würde bedeuten eine neue Branch anzulegen und so eine Version 1.* (Version mit alten Sprachvariablen) und eine Version 2.* (Version mit neuen Sprachvariablen) zu betreuen.
3) Oder man implementiert das neue Feature in irgendeiner Art und Weise, die abwärtskompatibel ist.

Da dies ein kniffeliges Problem ist, frage ich explizit nach der Abwärtskompatibilität. Welche Lösung schwebt dir da vor?

Meine Meining: Als jemand der apexx noch nutzt, sage ich dir ganz ehrlich ich werde nicht die Arbeit machen und durch alle Templates gehen und die Variablen anpassen.

**Comment by DOHRMANN-SOFTWARE** [comment]
Also heißt das nein.

Eigendlich wäre das Nummer 1.

Zu Nummer 2:
Aber man könnte es ja für Version 2 machen.
Bei größeren Version muss man ja immer Anpassungen vornehmen.
Denn ich hätte auch noch eine Menge anderer Ideen.
Man siehe es ja bei PHP.
Will man das es auch auf PHP 7 oder 8 läuft, oder lässt man es nur unter 5 laufen.

Zu Nummer 3:
Das wäre die Methode, mit der meisten Arbeit, und was das ganz noch mehr aufblähen würde.

**Comment by scheb** [comment]
Das heißt nicht zwingend "nein". Ich bin nur der Meinung das Feature ist "nett" weil man dann keine Konflikte in den Sprachvariablen mehr hat, aber es ist keine Revolution, die es rechtfertigen würde die Abwärtskompatibilität dafür aufzugeben.

Ich glaube ja eine abwärtskompatible Variante ließe sich durchaus implementieren. Warum nicht nicht Variablen im neuen und alten Stil generieren? Die neuen Variablen wären dann garantiert konfliktfrei, aber wen das nicht stört kann weiter die alten Variablen in den Templates lassen. Ich bin überhaupt nicht mehr drin im Code, aber soweit ich mich erinnere werden die Variablen irgendwo zentral eingelesen und für die Templates bereitgestellt. Es müsste relativ gut möglich sein, neben den alten Variablen auch noch zusätzliche im neuen Stil zu generieren. Alternativ könnte man auch über eine Option in der Konfiguration nachdenken, mit der man festlegen kann welche Stil man haben möchte.

**Comment by DOHRMANN-SOFTWARE** [comment]
Oh Gott!
Da hast du mir jetzt eine Nuss gegeben!

So wie ich das verstehe, müsste der Kern angepasst werden, wo man Admin-Center einstellen kann ob man den alten Typ oder den neuen Typ nutzen will.
Dann in der Sprachdatei eine Abfrage einfügen, die aus der Datenbank den Wert für den Typ ausließt, und die neuen Variabeln in einem IF-Block setzen.
Und die alten Variabeln bleiben unangetastet.
Das würde meiner Meinung nach die Abwärtskompatibilität sicherstellen.
Aber dann schleppt man Altlasten mit rum.
Die sollte man bei einem größeren Versionssprung dann aber wieder entfernen, so das das neu zum Alten bzw. Standard wird.

Die Idee halte ich für gut. (Nagut, du bist der Profi)
Was wäre mit einer kombination aus Nummer 4?

Eine zweite Sprachdatei halte ich für blöd.

Was mir aufgefallen ist, das ich schon viel an den Sprachdateien gemacht habe.
Da ich ich der Übersichtshalber auch die Sprachdatei für das Video-Modul angepasst habe.

Aber was mir als generelles Problem aufgefallen ist, wieviele Variabeln passen in den Speicher?
Oder erstellt PHP einen Cache und liest den gegebenfalls aus?

**Comment by scheb** [comment]
> So wie ich das verstehe, müsste der Kern angepasst werden, wo man Admin-Center einstellen kann ob man den alten Typ oder den neuen Typ nutzen will.
> [...]
> Das sich dieses Problem, ja hauptsächlich auf die Seitenutzer-Template besteht, kann man doch die Sprachdateien für die Admin-Oberfläche komplett auf den neuen Typ stellen?

Oh, Adminbereich ist ein gutes Stichwort. Sofern wir das mit einem Schalter lösen, darf der von der Einstellung nicht betroffen sein. Die Templates des Adminbereichs nutzen ja auch die Sprachvariablen und die willst du ja sicher nicht anpassen müssen wenn du den Schalter umlegst. Insofern sollte der Adminbereich bereits nur das neue Format verwenden, unabhängig was der Schalter sagt.

> Dann in der Sprachdatei eine Abfrage einfügen, die aus der Datenbank den Wert für den Typ ausließt, und die neuen Variabeln in einem IF-Block setzen.

Äh wirklich, so würdest du das machen? Einen If-Block in den Sprachdateien und dann im Endeffekt alle Variablen doppelt haben, einmal mit Präfix einmal ohne? Also so?

```php
if ($neueVariablen) {
    $lang['titles'] = array (
        'NEWS.SHOW' => 'Anzeigen',
    );
} else {
    $lang['titles'] = array (
        'SHOW' => 'Anzeigen',
    );
}
```

Wenn das dein Plan ist, tut mir leid, das machen wir ganz sicher nicht. Das ist doch Wahnsinn alle Variablen zu duplizieren und über die Zeit synchron zu halten. Du musst auf Dauer ja alles doppelt ändern. Stattdessen sollte das eine Funktion sein, die beim Laden der Variablen ausgeführt wird. Wenn "neue Variablen" angeschaltet ist, bekommen alle Variablen automatisiert den Modul-Namen als Präfix gesetzt. So ist das schön sauber an zentraler Stelle geregelt (im apexx Core) und die vielen Sprachdateien selbst müssen nicht angefasst werden.

> Ist es besser das im Kern zu machen, oder für jedes Modul selber?
> Denn modulbezogen macht es irgendwie wieder keinen Sinn.
> 
> Da wäre ich wieder bei meiner Frage der Aufteilung.
> So das man sich die Module herunterladen kann die man braucht bzw. die sich geändert habe.
>
> Die Idee halte ich für gut. (Nagut, du bist der Profi)
> Was wäre mit einer kombination aus Nummer 4?

In der Theorie ist das auch eine gute Idee, gerade wenn man ein modularisiertes System. Ich kann jedoch nur davon abraten jedes Modul als eigenständige Einheit mit eigenen Versionen zu entwickeln, die sich beliebig austauschen lassen. Ja, rein theoretisch ist jedes Modul eigenständig, aber apexx besitzt kein richtiges Dependeny-Management, also lässt sich nicht wirklich gut regeln welche Version von Modul A nun mit welchen Versionen von Modul B kompatibel ist. Das ist bei der Menge an Modulen ein verwaltungstechnischer Alptraum, denn man wird die vielen möglichen Versionen und Kombinationsmöglichkeiten irgendwann nicht mehr überblicken können. Selbst große Projekte wie [Symfony](https://github.com/symfony/symfony) versuchen das erst gar nicht und veröffentlichen alle ihre "Module" (bei ihnen heißt das "Components") gleichzeitig mit derselben Versionsnummer.

> Aber wieso so kompliziert?
> Man kann doch die neuen Variabeln mit den Präfixen einfach mit reinnehmen.
> Und bei einer neuen Hauptversion die alten löschen?

Wäre aktuell auch meine präferierte Lösung. Das wäre ja meiner Variante Nr. 3 "man implementiert das neue Feature in irgendeiner Art und Weise, die abwärtskompatibel ist."

> Aber was mir als generelles Problem aufgefallen ist, wieviele Variabeln passen in den Speicher?
> Oder erstellt PHP einen Cache und liest den gegebenfalls aus?

So viel Arbeitsspeicher wie eben da ist, in der Regel ist ein Limit auf den Servern eingestellt. Ich glaube aber kaum, dass die Sprachvariablen da ein Problem machen werden. Die Systeme heutzutage sind alle recht gut ausgestattet und apexx ist als Software winzig im Vergleich zu heute gängigen PHP Applikationen.

**Comment by DOHRMANN-SOFTWARE** [comment]
Na super!
Jetzt verwirrst du mich, und ich verstehe garnichts mehr!
Vielleicht liegt das daran, das ich meinen Text immer erweitert habe?

Die Idee mit dem If-Block war nur auf die neuen Varibeln bezogen.
Die Idee habe ich verworfen.

> Wenn das dein Plan ist, tut mir leid, das machen wir ganz sicher nicht. Das ist doch Wahnsinn alle Variablen zu duplizieren und über die Zeit synchron zu halten. Du musst auf Dauer ja alles doppelt ändern.

Das verwirrt mich total.
Die Variabeln duplizieren, ja. Aber was synchron halten?
Die alten Variabeln werden einfach nicht mehr angetastet.

> Stattdessen sollte das eine Funktion sein, die beim Laden der Variablen ausgeführt wird. Wenn "neue Variablen" angeschaltet ist, bekommen alle Variablen automatisiert den Modul-Namen als Präfix gesetzt. So ist das schön sauber an zentraler Stelle geregelt (im apexx Core) und die vielen Sprachdateien selbst müssen nicht angefasst werden.

Wie ich das verstehe, meinst du einen Konverter?

`/************** CONFIG **************/
$lang['config'] = array (
...
'PIC_POPUP_HEIGHT' => 'Maximale Höhe des Popup-Bilds:',
...

/* Neue Variabeln mit Präfixe */
...
'PRODUCTS_CONFIG_POPUPPICTUREMAXHEIGHT' => 'Maximale Höhe des Popup-Bilds:',
...
);`
So muss nur die Sprachdatei angepasst und gegebenfalls das Template angepasst werden, wenn man die neuen Variabeln nutzen will.
Format der neuen Variabeln:
MODULNAME_ARRAYNAME_VARIABELNAME

Ich habe die Variabeln weiter ausgeschrieben, weil HEIGHT ist ja was anderes als MAXHEIGHT ist.
Und wenn man HEIGHT mal braucht, hat man nicht das Problem mit der Kompatibilität.
Leider werden dadurch die Variabelnamen wesentlich länger, aber man kann sie besser zuordnen.

Ich dachte daran, wenn es nur ein Wort oder passend zur Variabel wie bei MAXHEIGHT ist, dann lässt man den Variabelnamen so, ist es ein längerer Text kommt noch ein MSG oder INFO hinzu.
So erkennt man ob es nur eine Bezeichnung oder eine Nachricht/Hinweis ist.

Der Nachteil des ganzen ist, das man mehr Speicher braucht.

**Comment by scheb** [comment]
> Das verwirrt mich total.
> Die Variabeln duplizieren, ja. Aber was synchron halten?
> Die alten Variabeln werden einfach nicht mehr angetastet.

Doch, sie müssen angefasst werden, um die Abwärtskompatibilität auch auf Dauer sicherzustellen. Wenn du neue Variablen im hinzufügst oder Variablen änderst, musst du das sowohl für den neuen, als auch den alten Stil machen. Denn du kannst ja nicht wissen, welchen Stil jemand bei sich verwendet.

> Wie ich das verstehe, meinst du einen Konverter?
> /************** CONFIG **************/
> $lang['config'] = array (`
> `...
> 'PIC_POPUP_HEIGHT' => 'Maximale Höhe des Popup-Bilds:',`
> ...
> /* Neue Variabeln mit Präfixe */
> ...
> 'PRODUCTS_CONFIG_POPUPPICTUREMAXHEIGHT' => 'Maximale Höhe des Popup-Bilds:',
> ...
> );

Das ist der Ansatz, den ich eben nicht möchte. Dann hast du alle Variablen doppelt, was meiner Meinung nach zum Einen unnötig ist, zum anderen Aufwand erzeugt um alte und neue Variablen synchron zu halten.

Was ich stattdessen tun würde, im Code ansetzen and dem Punkt wo die Variablen eingelesen werden. Hab das mal rausgesucht, wäre die Stelle hier:

https://github.com/scheb/open-apexx/blob/master/src/lib/class.language.php#L95-L102

Dort wird die `$lang` Variable aus der Sprachdatei gelesen, mit den User definierten Variablen zusammengefügt (`array_replace_recursive`). Am Ende, bevor die Variablen zurückgegeben werden, könnte man ein paar Zeilen Code hinzufügen, über alle Variablen in `$lang` iterieren und Kopien der Variablen hinzufügen, welche mit dem Modul-Namen gepräfixt sind. So bekommst du deine neuen Variablen vollautomatisch, ohne dass du die Variablen tatsächlich in der Sprachdatei duplizieren musst.

> Wieso hast du die Variabeln in unterschiedliche Arrays gesteckt?

Nur der Übersicht wegen. Hat keinen technischen Grund.

**Comment by DOHRMANN-SOFTWARE** [comment]
Jetzt verstehe ich noch weniger.

Wieso und wie Synchron halten?

Man lässt die alten Variabeln so wie sie sind drinne.
So stehen die alten Variabeln noch zur verfügung,  und man kümmert sich nur noch um die Variabeln die nach ```/ Neue Variabeln mit Präfixe */``` kommen.

Ich verstehe nicht woe das Ürpblem ist, das ist doch die einfachste Methode?

> Nur der Übersicht wegen. Hat keinen technischen Grund.

Ein Grund hat es vielleicht nicht, aber eine Auswirkung schon.

[public.php.txt](https://github.com/scheb/open-apexx/files/5358942/public.php.txt)

**Comment by scheb** [comment]
> Jetzt verstehe ich noch weniger.
> 
> Wieso und wie Synchron halten?
> 
> Man lässt die alten Variabeln so wie sie sind drinne.
> So stehen die alten Variabeln noch zur verfügung, und man kümmert sich nur noch um die Variabeln die nach `/ Neue Variabeln mit Präfixe */` kommen.

Weil du ansonsten das "Versprechen" der Abwärtskompatibilität brichst, wenn du alte und neue Variablen nicht gleichermaßen aktuell hältst und dich nur noch um die neuen Variablen kümmerst. Dann musst du das ganze wirklich als eine Version 2.* veröffentlichen.

> Ich verstehe nicht woe das Ürpblem ist, das ist doch die einfachste Methode?

Einfach vielleicht, aber nicht unbedingt am saubersten. In der Softwareentwicklung möchte man doch Duplizierung möglichst vermeiden und alle Variablen zu kopieren ist schon eine ziemlich große Duplizierung.

> Ein Grund hat es vielleicht nicht, aber eine Auswirkung schon.

Und die wäre? Mir fällt da nichts offensichtliches ins Auge. Aber wenn es irgendein Problem darstellt, dann können wir das ändern. Wie gesagt, es gibt keinen technischen Grund warum das so aufgebaut ist.

**Comment by DOHRMANN-SOFTWARE** [comment]
Vielleich kommt Verwirrung daher, das ich mit Abwärtskompatibilität meint, das man die alten Variabelname noch nutzen kann, aber das zukünftig nur noch an den neuen gearbeitet wird.

So das der Nutzer im Template noch die alten nuten kann, aber für das Überschreibungsproblem und neue Textausgabe die neuen nutzen muss.

> Und die wäre? Mir fällt da nichts offensichtliches ins Auge. Aber wenn es irgendein Problem darstellt, dann können wir das ändern. Wie gesagt, es gibt keinen technischen Grund warum das so aufgebaut ist.

Das Problem für mich ist, da ich nicht weiss, welches Array in welchem Bereich genutzt wird, da ich nicht im Code stecke.
Zum Beispiel die SORTBY-Variabel. Die wird einmal in dem products- und dem manufacturers-Array genutzt.
Es ist schon ein Unterschied.
Meine Idee, mit die Variabeln dan das Modul zu binden, hast du an Funktionen gebunden.
Und wenn man nicht genau weiss, welche Funktion exakt genutzt wird, ist eine zuordnung im Template schwer.
Wirklich problematisch halte ich es nur, wenn man ein neues Modul erstellt, oder ein vorhandenes um Funktionen erweitert.
So wie ich es rausgefunden habe, sind die Datein ```lib\class.language.php``` und  glaube ich die ```lib\class.apexx.php``` zuständig.
Das Problem ist halt die Unwissenheit. Aber die kann man ja lösen, in den man den betreffenden Bereich in der Sprachdatei angibt.
Das mit den Arrays hast du auch in der Anleitung angesprochen.
Die Angaben der Bereich halte ich auch für die ```XXX_byuser.php``` für wichtig.

**Comment by scheb** [comment]
> Vielleich kommt Verwirrung daher, das ich mit Abwärtskompatibilität meinte, das man die alten Variabelname noch nutzen kann, aber das zukünftig nur noch an den neuen gearbeitet wird.

Ja, den Eindruck habe ich auch. Aber Abwärtskompatibilität nur von einer Minor-Version zur nächsten Minor-Version sicherzustellen reicht halt nicht. Kompatibilität brechen darfst du eigentlich nur wenn du eine neue Major-Version veröffentlichst (also z.B. Versionssprung von 1.* auf 2.0).

> Bei der Methode den Code zu ändern, gäbe bei mir folgendes Problem:
> Du nutzt bei den Array wo den Produktypen angegeben sind book anstatt literature obwohl von Literatur die Rede ist. Und es sind mehrere solcher Fälle vorhanden.

Das eine sind halt die Platzhalter, das andere sind die sichtbaren Texte. Ja, die sind manchmal etwas inkonsistent, vermutlich weil sich im Laufe der Entwicklung der Text geändert hat. Das ist zugegebenermaßen nicht schön, letztendlich für mich kein Grund auch noch die Variablennamen zu ändern und so ein unübersichtliches Chaos zu stiften für jemand der Upgraden möchte (außer du würdest jede umbenannte Variable inkl. ihres neuen Namens protokollieren). Also für mich ist das ein ganz anderes Unterfangen, unabhängig von den Variablenpräfixen die wir gerade diskutieren.

> Das Problem für mich ist, da ich nicht weiss, welches Array in welchem Bereich genutzt wird, da ich nicht im Code stecke.
> Zum Beispiel die SORTBY-Variabel. Die wird einmal in dem products- und dem manufacturers-Array genutzt.
> [...]

Das kann ich dir leider auch nicht mehr sagen, nach welchem Schema das strukturiert ist. Ich glaube der einzige Grund dafür war, das man "logische Gruppen" mit Variablen hat, die in irgendeiner Form zusammengehören und immer gemeinsam geladen werden. Und der Grund dafür ist wohl, dass ich damals (unter PHP4) sehr auf die Performance bedacht war und möglichst wenig unnötige Inhalte laden wollte - um Speicher und Rechenzeit zu sparen. Inzwischen hat sich aber vielen getan in PHP. Ich glaube aus heutiger Sicht ist das alles ein unnötiger Overhead, da der Performance-Gewinn wahrscheinlich kaum zu messen ist. Ich halte es sogar für wahrscheinlich, dass es heutzutage sogar schneller wäre einfach pauschal alle Variablen zu laden anstatt Rechenzeit für das einzelne Laden dieser Blöcke zu investieren.

Mit `lib\class.language.php` und `lib\class.apexx.php` bist du übrigens richtig. Das sind die beiden Core Klassen, die für das Laden der Sprachvariablen zuständig sind.

---

Ich verstehe definitiv dein Wunsch

1) für konfliktfreie Variablen zu sorgen
2) manchen Variablen bessere Namen zu geben, die ihren Inhalt besser repräsentieren.

Was mir allerdings sorgen macht, aus Sicht eines normalen Apexx-Seitenberreibers bedeuten diese beiden Änderungen nahezu keinen Gewinn, denn:

- es ist vollkommen egal wie die Variablen heißen, sobald die Templates erst mal angepasst sind, macht man ja schließlich nicht jeden Tag
- jemand der bereits eine Apexx-Seite betreibt hat mit hoher Wahrscheinlichkeit gar kein Problem mit den Variablen und sieht daher keinen Grund daran etwas zu ändern (zu der Fraktion zähle ich mich, ich bin froh dass die Seite noch läuft, aber Arbeit reinstecken möchte ich nicht).

Dem gegenüber steht ein vergleichbarer großer Aufwand um auf neue Variablen zu aktualisieren, mit dem Ergebnis dass die Website am Ende... nun... absolut genauso aussieht wie vorher. Insofern plädiere ich stark dafür, dass wir eine kompatible Lösung schaffen, mit der wir es vermeiden die Seitenbereiber zu zwingen "viel Aufwand für Nichts" hinzunehmen.

Die große Frage ist: wie machen wir nun hier weiter?

**Comment by DOHRMANN-SOFTWARE** [comment]
Mein Favorit ist ja, die Variabeln zu duplizieren, sie umbennen und nur die neuen zu benutzen.

Aber um dich zufrieden zu stellen, schlage ich folgendes vor:
Neue und konfliktbehaftete Variabeln nach dem neuen Systen, die alten so lassen, und bei einer neuen Major-Version die Variabeln kommplett auf das neue System setzten, aber dann nicht nur die Sprachdateien anpassen, sondern den Kompletten Code des Moduls.

Ich habe noch einen guten Grund dafür gefunden.
Für zukünftige Entwicklungen an APEXX ist es besser die verwirrungen zu beseitigen.

Ich verstehe immer noch nicht von das Problem der doppelten Variabeln ist, und was du mit synchron halten meinst.
Aber egal.

Die Änderungen an den Variabeln und an dem Code schreibe ich in eine Verlaufsdatei, damit ich auch selber sehe was ich geändert habe.

Das System mit den unterschiedlichen Arrays würde ich dann, wenn überhaupt, bei einer neuen Major-Version des Haupt-Moduls ändern.
Denn wenn ich das richtig sehe, ist da nichts mit der Abwärtskompatibilität zu machen, da man alle Module dafür anpassen müsste.

**Comment by scheb** [comment]
Damit wir hier mal weiter kommen, magst du vielleicht mal für eine Datei exemplarisch die Änderungen durchführen und als Pull Request einstellen? Bringt wahrscheinlich mehr das an einem konkreten Beispiel zu diskutieren.
