### ISSUE TITLE
Poll: PHP-Fehler bei mehrfacher Auswahl

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#20]
Beim Absenden der Auswahl spuckt PHP einen Fehler bzw. eine Info aus:

>Warning: Invalid argument supplied for foreach() in poll.php on line 99

`foreach ( $_POST['vote'] AS $aid => $true ) {`
`$aid=(int)$aid;`
`if ( !$aid || $aid<1 || $aid>20 || $true!='1' ) continue;`
`$cset[]='a'.$aid.'_c=a'.$aid.'_c+1';`
`}`

Kann da jemand etwas mit anfangen?

**Comment by scheb** [comment]
Reduziere das Error Log Level von PHP, so dass Warnings nicht angezeigt werden. Ist für ein Produktivsystem generell empfehlenswert die PHP Fehler (egal welches Level) nicht anzuzeigen machen, weil das Rückschlüsse auf das darunterliegende System zulässt.

**Comment by bigfraggle** [comment]
Mit der Antwort verrutscht?
Vrgl. https://github.com/scheb/open-apexx/issues/21#issuecomment-399982654

**Comment by scheb** [comment]
Nein, ist auch nur eine Warning, die man mmn ignorieren kann.

**Comment by bigfraggle** [comment]
Nein, die Votes werden nicht gespeichert.

**Comment by scheb** [comment]
Müsste man halt mal schauen, wie die Daten aussehen, die da ankommen, sprich `var_dump($_POST);`. Eventuell werden die Daten in einem falschen Format an den Server gesendet und deshalb funktioniert's nicht.

**Comment by bigfraggle** [comment]
Habs nicht lösen können. Falls jemand, der sich besser damit auskennt, mal Zeit und Muße hat, freue ich mich über Tipps zur Lösung. Bis dahin gibt's halt keine Mehrfach-Votes.
