### ISSUE TITLE
PHP 7.2 Warnung

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#21]
Habe mich jetzt mal getraut und ein Projekt von PHP 5.6 auf 7.2.6 aktualisiert.
Dazu habe ich apexx 1.8.0 vom Mai hochgeladen.

Grundsätzlich funktioniert die Seite (soweit ich das sehe), allerdings gibt es beim Seitenaufruf diese zwei Warnungen zu sehen:

>Warning:  Declaration of database::query($query) should be compatible with mysqli::query($query, $resultmode = NULL) in lib/class.database.mysqli.php on line 308

>Warning:  count(): Parameter must be an array or an object that implements Countable in lib/functions.public.php on line 353

Im Adminbereich taucht auf manchen Seiten zudem diese Warnung auf:

>Warning: Use of undefined constant SID - assumed 'SID' (this will throw an Error in a future version of PHP) in lib/class.templates.admin.php on line 37

Kann da jemand etwas mit anfangen?

**Comment by scheb** [comment]
Reduziere das Error Log Level von PHP, so dass Warnings nicht angezeigt werden. Ist für ein Produktivsystem generell empfehlenswert die PHP Fehler (egal welches Level) nicht anzuzeigen machen, weil das Rückschlüsse auf das darunterliegende System zulässt.

**Comment by bigfraggle** [comment]
Ja, habe ich schon gemacht. Also ist die Meldung soweit "normal" bzw. unbedenklich?

**Comment by scheb** [comment]
Ja. Ist nicht schön, aber unbedenklich.

**Comment by bigfraggle** [comment]
Danke
