### ISSUE TITLE
setup-file

### ISSUE THREAD

**Issue by TigerClaw33** [scheb/open-apexx#22]
Hallo,
kurze Frage aber wo befindet sich der setup-Ordner? Ich kann diesen nicht sehen ...

**Comment by bigfraggle** [comment]
Gute Frage...

Bei der 1.7.3 war er noch dabei. Einfach runterladen und schauen, ob es damit funktioniert.
https://github.com/scheb/open-apexx/releases

**Comment by scheb** [comment]
Der ist offenbar irgendwann mal verloren gegangen. Habe ihn wiederhergestellt.

**Comment by bigfraggle** [comment]
Beim Setup-Aufruf gibt es unter PHP 7.2 einen Fehler:

> Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in setup/class.apexx.php:76 Stack trace: #0 setup/class.apexx.php(56): apexx->prepare_vars() #1 setup/index.php(43): apexx->apexx() #2 {main} thrown in setup/class.apexx.php on line 76

**Comment by bigfraggle** [comment]
Wenn man das `@set_magic_quotes_runtime(0);` in Zeile 76 löscht, geht die Installation. Allerdings kommt danach ein Haufen von Deprecated-Fehlermeldungen, dass es nicht mehr schön ist. Grundsätzlich funktioniert es aber.

**Comment by scheb** [comment]
set_magic_quotes_runtime() ist unter PHP7 nicht mehr verfügbar. Habe die Zeile entsprechend modifiziert.

Zu den deprecated Fehlermeldungen: Das sind keine richtigen Fehler, sonden nur Warnhinweise, dass diese funktionen in der zukünftigen PHP Version nicht mehr verfügbar sein werden. Dementsprechend sollten die in der PHP error reporting Konfiguration deaktiviert werden.
