### ISSUE TITLE
Mal wieder Twitter

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#24]
Die Twitter-Problematik ist ja nicht neu, liegt ja auch schon seit Ewigkeiten ein Pull request hier rum... (https://github.com/scheb/open-apexx/pull/2)

Wie auch immer versuche ich gerade bei einem bestehenden Projekt die Twitter-Integration hinzuzufügen. Nachdem die Dateien aus dem o.g. Pull request anfangs funktioniert haben, klappt das Ganze jetzt überhaupt nicht mehr. Anscheinend hat Twitter da einiges umgestellt, wobei bei bestehenden Projekten die Twitter-Anbindung weiterhin wunderbar funktioniert.

Die Links "Jetzt konfigurieren" in der Moduleinstellung funktionieren jedenfalls nicht mehr.

> Fatal error: Uncaught EpiOAuthException in /modules/twitter/epitwitter/class.epioauth.php:375 Stack trace: #0 /modules/twitter/epitwitter/class.epioauth.php(350): EpiOAuthException::raise(Object(EpiCurlManager), false) #1 /modules/twitter/epitwitter/class.epioauth.php(48): EpiOAuthResponse->__get('oauth_token') #2 /modules/twitter/admin.php(57): EpiOAuth->getAuthorizeUrl(Object(EpiOAuthResponse), Array) #3 /lib/class.apexx.admin.php(71): action->connect() #4 /admin/action.php(24): apexx_admin->execute_action() #5 {main} thrown in /modules/twitter/epitwitter/class.epioauth.php on line 375

Daraufhin habe ich die Verbindung bei developer.twitter.com händisch angelegt und mir die benötigten Tokens so geholt, wobei die jetzt anders heißen. Es gibt einmal zwei "Consumer API keys" ("API key" sowie "API secret key") und "Access token" sowie "Access token secret". Von der Länge her verglichen mit meinen vorherigen Projekten scheinen es die beiden letzten zu sein.

Wie auch immer: es funktioniert nicht. Der Cronjob an sich läuft, zumindest wird die Zeitangabe bei "lastexec" in der DB aktualisiert. Bei der Verknüpfung zu Twitter, die apexx früher automatisiert vorgenommen hat, muss also noch irgendwas anderes passiert sein. Nur was...?!?

Freue mich über Ideen...

**Comment by bigfraggle** [comment]
Niemand hier, der sich mit der Twitter API auskennt?

**Comment by White4Shadow** [comment]
Naja ich könnte nochmal gucken, aber da mein anderer request nie beachtet wurde muss ich mal sehen 



Am 29.10.18 um 17:57 schrieb Marc

**Comment by scheb** [comment]
War wohl zu lange inaktiv gewesen, als dass ich das beachtet hätte. Aber so wie ich das verstanden habe, ist auch die "gefixte" Version mittlerweile nicht mehr funktionsfähig, oder seh ich das falsch?

**Comment by bigfraggle** [comment]
So ist es. Die gefixte Version funktioniert mittlerweile nicht mehr. Twitter hat da mal wieder irgendetwas umgestellt.

**Comment by scheb** [comment]
Ja, ich glaube mitbekommen zu haben, dass sie ihre alte API irgendwann neulich abgeschaltet haben. Also wenn wir irgendwer einen Fix bringt und irgendwer anderes das zeitnah bestätigen kann, dass es funktioniert, dann werde ich das gerne mergen.
