### ISSUE TITLE
Update Version von 1.7.x auf 1.8.1

### ISSUE THREAD

**Issue by wocky1968** [scheb/open-apexx#25]
Ich benötige dringend eine reine Update Version von 1.7.1 auf 1.8.1
Mein Provider hat PHP5.6 abgeschaltet und auf PHP7.2 upgedatet.

Jetzt liegen 3 Seiten auf dem Boden.
Mit der hier liegenden Version 181 habe ich es versucht, es aber nicht geschafft.
Ich bräuchte eine Anweisung wie die das Update auf 1.8.1 durchführe, damit ich meine Seiten wieder betreiben kann.... Please HELP

**Comment by bigfraggle** [comment]
Wo ist denn genau das Problem?
Wenn du die aktuelle Version auf den Server kopierst, sollte es lediglich noch ein paar Warnhinweise geben, die du in der php.ini ausschalten kannst.

Fehlermeldungen?
Oder besser noch ein Link?

**Comment by wocky1968** [comment]
Ehrlich gesagt habe ich keine Ahnung von PHP, ich kann Anweisungen umsetzten und auch durch logisches denken und ein bisschen Erfahrung gewisse Sachen selber machen.
Im src Ordner ist ein Setup Ordner, den es normalerweise nur bei der Erstinstallation gibt sonst nicht.
Ich musste bis jetzt nur Dateien kopieren bzw überschreiben und fertig.
Es gab früher immer ein "normales" Neu-Installationspaket und ein Updatepaket.

**Comment by bigfraggle** [comment]
Ein Updatepaket gibt es nicht mehr - im Grunde wurden eh nur wenig Änderungen gemacht. Also einfach die neuen Dateien kopieren und ggf. eigene Änderungen im Code berücksichtigen. Das Setup wird nur für Neuinstallationen benötigt.

**Comment by wocky1968** [comment]
Also alle Ordner rüberkopieren und überschreiben bis auf den Setup Order und den Template Ordner?
Im Template Order sind ja meine angepassten Templates.
Forum habe ich nicht, ist eine normale Hompage mit statischen Seiten.

**Comment by bigfraggle** [comment]
Ja, Templates behalten und die lib/config.php natürlich auch. Wenn du sonst keine Anpassungen hast, kannst du den Rest kopieren. Trotzdem Backup nicht vergessen.

**Comment by scheb** [comment]
Hallo Frank,

ja, ich habe deine Emails bekommen, fand aber bisher nicht die Zeit dir zu antworten, aber ich sehe jetzt, dass es offenbar eine gewisse Dringlichkeit gibt, also nehme ich mir nun die Zeit. Allerdings ist mir unverständlich, wie du einfach solange warten konntest, dass der Provider dich nun zwingt auf PHP7.2 zu upgraden. Ich bin mir sicher das Zwangsupgrade wurde nicht einfach so über Nacht gemacht, sondern mit entsprechender Vorwarnzeit. Aber sei's drum, jetzt sehen wir erst mal, dass wir dein Problem lösen. Ich antworte jetzt bewusst hier auf Github, vielleicht helfen die Anweisungen ja noch jemand anderem, der vor demselben Problem steht. Passiert in letzter Zeit ja immer öfter, dass die Hoster von antiken PHP-Versionen weg wollen, die nicht mehr gepflegt werden (sprich: Sicherheitsupdates).

Also zunächst mal: Nein, es gibt keine Updatepakete mehr und wird es auch nicht geben. Macht aber nichts, das Update ist auch ohne Updatepaket mit der Komplettinstallation möglich.

Ich setze mal voraus, dass die apexx Installation "original" ist, also keine Modifikationen an den Dateien der Software (außer Templates und Grafiken) vorgenommen worden. Falls das so ist, werden diese nun überschrieben und müssten ggfs. wieder hinzugefügt werden.

**Vorbereitung**
- Backup der Seite im aktuellen Zustand, d.h. Dateisystem und Datenbank - unbedingt machen weil ich die nun folgenden Updateanweisungen "blind" geschrieben habe, also nicht selbst getestet habe.
- Lade dir die aktuelle Version von Github als ZIP herunter.
- In dem ZIP befindet sich ein Ordner "src", das ist die klassische Komplettinstallation von apexx. Alles andere ist für das Update nicht relevant und kannst du somit ignorieren.

**Durchführung**

- Alle PHP-Dateien im Hauptordner überschreiben
- Folgende Ordner werden überschreiben:
  - admin
  - forum (falls verwendet, die Ordner mit den Grafiken ggfs. nicht überschreiben)
  - language (nicht zwingend erforderlich, insbesondere wenn Änderungen an den Texten gemacht wurden, evtl. überspringen oder mit einem Diffing-Tool z.B. WinMerge, die Änderungen zusammenführen)
  - lib (außer der Config-Datei, ggfs. aus dem Backup übernehmen)
  - modules
- Die Seite sollte nun wieder in einem lauffähigen Zustand sein.
- Im Adminbereich anmelden und die Updates der Module ausführen.

**Bekannte Probleme**

Wenn die Seite PHP-Fehler vom Typ "Notice" oder "Warning" anzeigt, in die Config einfügen:
```php
error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED ^ E_USER_DEPRECATED);
```

Wenn die Sonderzeichen nicht richtig angezeigt werden, in die Config einfügen:
```php
ini_set("default_charset", "ISO-8859-1");
```

**Comment by wocky1968** [comment]
Hallo Christian,
ja du hast recht es gab Ankündigungen, ich habe mir aber gedacht, wie damals von 55 auf 56 das da nichts zu machen ist. Sorry, mein Fehler.
Ich habe jetzt alles rüber kopiert aus dem src ausser Setup und Templates und Forum.
Habe die config.php original auch aus dem BU wieder rein kopiert.
Habe /admin gestartet, aber es passiert nichts.... leere Seite... www.tambourcorps-eller.de
keine Fehlermeldung.... (habe gestern natürlich was rumgespielt, aber denke ich habe nichts großartig verändert)

**Comment by scheb** [comment]
Also offenbar gibt es irgendeinen Fehler, der nicht angezeigt wird (vermutlich aus Sicherheitsgründen). Dann lass uns mal alle Fehler sichtbar machen, dazu fügst du vorrübergehend in die Config ein, anstelle der `error_reporting` Zeile:

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Wenn nichts zu Tage fördert, musst du mal in die Fehler Logdatei von PHP oder des Webservers schauen, was dort steht. Hängt von deinem Hoster ab, wie man da ran kommt, kann ich dir leider nicht sagen.

**Comment by wocky1968** [comment]
Also so:
// DEBUG ///////////////////////////////////////////////////////////////////////////////////

// Kritische Fehlermeldungen anzeigen (true/false)
$set['showerror'] = true;

// Fehler-Report am Ende zeigen (true/false)
// $set['errorreport'] = false;
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


// Cache immer ausgeben (true/false)
$set['outputcache'] = false;

// Renderzeit anzeigen (true/false)
$set['rendertime'] = false;

// Anfang und Ende der Templates anzeigen
// 0 = aus
// 1 = durch HTML-Kommentare
// 2 = sichtbare Rahmen
$set['tmplwhois'] = 0;
ini_set("default_charset", "ISO-8859-1");
?>

**Comment by scheb** [comment]
Ja, das passt so.

Achja, ein Problem mit der .htaccess könnte es auch sein, sofern du die ebenfalls überschrieben hast. Im Zweifelsfall die alte wiederherstellen.

**Comment by wocky1968** [comment]
bei mir steht das die vorher schon deaktiviert waren: .htaccess_deactivated
ist aber schon länger so.....

**Comment by wocky1968** [comment]
jetzt werden Fehlermeldungen ausgegeben....

**Comment by scheb** [comment]
Das hier fehlt in deiner Config:

```php
$set['mysql_api'] = 'mysqli';
```

Bitte nicht vergessen die temporären Änderungen wieder entfernen.

**Comment by wocky1968** [comment]
ok, habe ich eingefügt....
jetzt erscheint schon mal meine Seite.......

**Comment by wocky1968** [comment]
es scheint zu funktionieren... :-)
Ich brauchte im admin nur ein Modul zu aktualisieren (Produktdatenbank) sonst nichts.
Unter Version erscheint 1.8.1
Aktuelle Version 1.7.1

**Comment by bigfraggle** [comment]
In Sachen SSL-Verschlüsselung solltest du die Seite eh mal optimieren.

https://www.redirect301.de/weiterleitung-http-nach-https/#redirect-von-http-zu-https

**Comment by wocky1968** [comment]
Die Version stimmt, aber die akutelle Version nicht...
mich stört es nicht.... denke das ist wenn es eine neuere gibt und updaten könnte.....

**Comment by wocky1968** [comment]
Noch mal eine letzte Frage, bis welcher PHP Version ist das jetzt kompatibel ?
Version 7.x oder nur bis einer bestimmten?
Heisst ab wann muss ich wieder drauf achten ;-)

**Comment by bigfraggle** [comment]
Solange bis als deprecated eingestufte Befehle, die apexx verwendet, aus PHP endgültig rausfliegen. Wann das der Fall ist, wird sich zeigen. Denke mal spätestens mit Version 8 wird es Handlungsbedarf geben. Am besten in Sachen PHP immer aktuell bleiben und neue Versionen zeitig ausprobieren. Wenn es dann Probleme gibt, kann man in Ruhe nach Lösungen suchen.

**Comment by wocky1968** [comment]
Nochmal vielen lieben Dank....
Vielleicht solltest du immer so eine "Anweisung" dazu schreiben für Updates ;-)
Ich denke das noch mehr das Problem haben, ausser die kennen sich so aus wie dich :-)
So hat mir das super geholfen nach den Anweisungen....
Ich weiß ist jetzt open Source , aber hast es halt programiert :-)

**Comment by wocky1968** [comment]
Hallo,
habe noch mal eine Frage...
die Updates haben soweit funktioniert auf den Seite....
Ich habe noch eine Seite, da werden keine Inhalte angezeigt und weiß nicht woran das liegen könnte..... 

https://www.schuetzenverein-eller.de/content.php?id=54

**Comment by wocky1968** [comment]
Es wird kein Content angezeigt, wenn es kein Modul ist.....

**Comment by bigfraggle** [comment]
Vielleicht mal wieder Fehlermeldungen aktivieren...

**Comment by wocky1968** [comment]
ok, welche? die vom Provider oder in der config.php ? oder beide?

**Comment by wocky1968** [comment]
Habe die Fehlermeldungen aktiviert wie oben beschrieben in der config.php...
Es kommen aber keine Fehler......

**Comment by wocky1968** [comment]
Im Logfile des Providers und Logfile PHP7.2 kommen diese Fehler:

[Mon Oct 29 09:18:40 2018] [php7:error] [pid 23032] [client 142.93.204.160] [host schuetzenverein-eller.de] script '/is/htdocs/wp1154808_PK2HMKKV7M/www/cms/xmlrpc.php' not found or unable to stat
[Mon Oct 29 09:36:29 2018] [ssl:warn] [pid 25289] [client [host AH01909: schuetzenverein-eller.de:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 29 09:36:29 2018] [ssl:warn] [pid 25289] [client [host AH01909: sv-eller.de:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 29 09:37:29 2018] [ssl:warn] [pid 25289] [client [host AH01909: schuetzenverein-eller.de:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 29 09:37:29 2018] [ssl:warn] [pid 25289] [client [host AH01909: sv-eller.de:443:0 server certificate does NOT include an ID which matches the server name

**Comment by wocky1968** [comment]
Wenn ich mit dem editor die statischen Seiten bearbeite, ist alles da und zu sehen.
Nur auf der Website wird der Inhalt der Staischen Seite nicht angezeigt.....
