### ISSUE TITLE
Statische Seite werden nicht angezeigt

### ISSUE THREAD

**Issue by wocky1968** [scheb/open-apexx#26]
Nach dem Update auf Version 1.8.1 werden die Inhalte der statischen Seiten nicht angezeigt.
PHP ist 7.2
Fehlermeldungen sind nicht zu erkennen (für mich auf jeden Fall nicht)
www.schuetzenverein-eller.de
Wer kann mir hier helfen?

**Comment by wocky1968** [comment]
Fehlermeldung in der config.php ist eingeschaltet, aber nichts zu sehen......
Im Logfile des Webhosters ist auch nichts zu erkennen.

**Comment by scheb** [comment]
Ehrlich gesagt, keine Ahnung. Ich habe bei mir selbst mehrere Apexx auf 7.2 laufen und mit den statischen Seiten bisher keine Probleme gehabt.

1) Mache zur Sicherheit bitte mal den "cache"-Ordner leer.

2) Wenn du mit "Fehlermeldungen in der config.php" die Option `$set['showerror']` meinst, die wird uns nicht weiterhelten. Wir sollten mal die PHP-Fehlermeldungen wieder anschalten, also die Zeile mit `error_reporting` in der Config ersetzen durch:

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

Das wird einiges an Fehlern anzeigen, vielleicht ist da ja etwas relevantes dabei.

3) Dann sollten wir nachschauen, ob überhaupt irgendwelche Inhalte aus der Datenbank ausgelesen werden. Dazu nach dieser Zeile hier: https://github.com/scheb/open-apexx/blob/master/src/content.php#L84
ein `var_dump($res);` einfügen.

**Comment by wocky1968** [comment]
Cache Ordner habe ich auch schon geleert.
Genau das habe ich schon gemacht in der config.php - aber keine Fehler zu sehen.....

den 3. Punkt habe ich nicht verstanden......

**Comment by scheb** [comment]
> Genau das habe ich schon gemacht in der config.php - aber keine Fehler zu sehen.....

Dann müsste die Seite aber voll mit PHP-Fehlern sein. So hilft mir das nichts weiter.

> den 3. Punkt habe ich nicht verstanden......

In deiner content.php, nach der Zeile, die ich markiert habe, ein `var_dump($res);` einfügen.

**Comment by wocky1968** [comment]
habe ich gemacht

**Comment by scheb** [comment]
Gut, kannst du wieder entfernen.

Dann mal nach dieser Zeile hier: https://github.com/scheb/open-apexx/blob/master/src/content.php#L122
ein `var_dump($content);`

**Comment by wocky1968** [comment]
erledigt

**Comment by scheb** [comment]
Bitte mal das "glossar"-Modul deaktivieren

**Comment by scheb** [comment]
Jetzt sind die Inhalte ja wieder da. Dann liegt's am "glossar"-Modul. Benötigst du das? Ansonsten einfach deaktiviert lassen. Was mich auch mal interessieren würde, hast du im Glossar irgendwelche Einträge?

Das `var_dump($content);` bitte wieder entfernen.

**Comment by wocky1968** [comment]
hm, nein benötigen nicht direkt. Ich habe aber ich habe Einträge da drin ja.
Erklärungen zu bestimmten Sachen.
