### ISSUE TITLE
Fehlermeldung bei der Druckfunktion

### ISSUE THREAD

**Issue by Claus1965** [scheb/open-apexx#27]
Hallo Zusammen,
ich habe bei meinen apexx-Websites nach dem Update auf php 7.x nun bei der Druckfunktion/ Druckansicht immer folgende Fehlermeldung:
error: "WEBSITE_NAME" is already defined!

**Comment by Claus1965** [comment]
Hallo, hat keiner eine Idee, wie man die Fehlermeldung beseitigen könnte?

**Comment by bigfraggle** [comment]
Kann dir leider nicht helfen, da ich die Druckansicht nicht nutze.

**Comment by Claus1965** [comment]
Ok, danke. Vielleicht hat ja Christian eine Idee, woran es liegen kann.

**Comment by DOHRMANN-SOFTWARE** [comment]
Entschuldigung, das ist mein Fehler.
Ich habe diese Variabel woanders platziert, weil der angegeben Webseitenname im Admin-Bereich nicht für die Druckseiten genutzt wurde, und wuste nicht, das ich damit einen Fehler auslösen würde.
Ich suche mal die Stelle raus, und ändere sie hier.
