### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by wocky1968** [scheb/open-apexx#31]
Hallo Zusammen,
ich habe immer noch ein Problem beim Editor... oder Medienmanager?
Wenn ich im Fotoeditor ein Bild raussuche im Medienmanager und das Icon anklicke übernimmt der nicht das Bild auf die Seite bzw Editor sondern schreibt einfach nur "True"....
Konnte mir helfen indem ich den Link händisch einfüge, aber der andere Weg ist einfacher ;-)

Bildeigenschaften-> Server durchsuchen > den Foto Pfad > dann Foto suchen > klick auf Icon mit Pfeil auf Umschlag

Kann mir da jemand helfen?

**Comment by bigfraggle** [comment]
Hm, das ist auf jeden Fall kein grundsätzlicher Fehler. Zumindest kann ich das hier nicht reproduzieren...
