### ISSUE TITLE
Macht es noch Sinn etwas beizutragen?

### ISSUE THREAD

**Issue by DOHRMANN-SOFTWARE** [scheb/open-apexx#32]
Hi
Macht es noch Sinn etwas beizutragen, oder ist es besser eine Abspaltung zu machen?
Das Forum wurde ja leider wegen mangelndem Intresse geschlossen.

Ich passe ja noch für mich das Produktdatenbank- und Dowloads-Modul an.

Ich komme mit Github ja leider nicht klar.

**Comment by bigfraggle** [comment]
Ich bin noch am Ball... So ein bisschen vermisse ich das Forum auch. War doch einfacher.

**Comment by DOHRMANN-SOFTWARE** [comment]
Auf meiner Seite könnte ich ein Forum einrichten.
Aber da habe ich wegen der rechtlichen Sache muffensausen.

**Comment by scheb** [comment]
> Macht es noch Sinn etwas beizutragen, oder ist es besser eine Abspaltung zu machen?

Was würde denn durch einen Fork besser werden? Das würde ja an der Situation nichts ändern, dass es offenbar niemanden gibt, der dieses Projekt weiterentwickeln möchte. Das könnte man hier in diesem Repository ja bereits tun.

> Das Forum wurde ja leider wegen mangelndem Intresse geschlossen.

Das in Kombination mit den neuen DSGVO-Richtlinien. Auch hier frage ich mich allerdings, wozu benötigst du ein Forum? Das Interesse im alten Forum war am Ende derart gering, also wieso sollte das in einem neuen Forum anders sein? Wenn du einen Ort möchtest um sich unter den Entwicklern auszutauschen, gibt es sicherlich Möglichkeiten (geschlossenes Forum, Discord, Slack). Ich stimme dir da allerdings zu dass GitHub dafür nicht unbedingt der beste Ort ist.

**Comment by DOHRMANN-SOFTWARE** [comment]
> Was würde denn durch einen Fork besser werden? Das würde ja an der Situation nichts ändern, dass es offenbar niemanden gibt, der dieses Projekt weiterentwickeln möchte. Das könnte man hier in diesem Repository ja bereits tun.
Besser nicht unbedingt, aber ich habe Änderungen vor die dir vielleicht zuwider sind.
Und du musst ja, weil du hier der Chef bisst, jede Änderungen überprüfen und genehmigen, und wenn du auch nicht mehr aktiv an dem Projekt arbeitest ist das auch blöd.

> Auch hier frage ich mich allerdings, wozu benötigst du ein Forum?
Weil Github dafür ungeignet ist, und um sich besser auszutauschen zu können als hier.
Ich weiss, das hier nichts los ist, aber irgendwo muss man ja was machen, sonnst is eine Abspaltung für die Leute die daran noch arbeiten (auch wenn es nicht viel ist) besser.

**Comment by scheb** [comment]
> Besser nicht unbedingt, aber ich habe Änderungen vor die dir vielleicht zuwider sind.
> Und du musst ja, weil du hier der Chef bisst, jede Änderungen überprüfen und genehmigen, und wenn du auch nicht mehr aktiv an dem Projekt arbeitest ist das auch blöd.

Anscheinend gibt es eine gewisse Unsicherheit, ob ich Weiterentwicklungen überhaupt akzeptieren würde und daher der Wunsch nach einem Fork in dem man sozusagen "machen kann was man möchte". Nun, ich sehe dieses Projekt mittlerweile ziemlich emotionslos. Ich würde jedes neuen Feature annehmen, das sinnvoll ist und für das es Interesse von anderen Nutzern gibt. Deine Idee mit selbstbestimmter Weiterentwicklung und dafür einen Fork zu machen geht allerdings nur auf, wenn du der einzige bist der daran arbeitet. Sobald du im Team arbeitest, wirst du wieder das gleiche Problem haben, das man sich irgendwie einigen muss was man implementiert und wie man es implementiert. Insofern kann es für dich als einzelner Entwickler eine Lösung sein, die Herausforderungen eines gemeinschaftlichen Open Source Projekts wird das allerdings auch nicht lösen, sondern nur wo anderes hin verschieben.

Da sich bisher niemand hervorgetan hat, der das hier ernsthaft weiterentwickeln möchte, bin ich nun mal noch der einzige Maintainer. Da ich aber selbst nichts mehr daran mache, hätte ich kein Problem damit das Repository auch für andere (vertrauenswürdige) Nutzer freizugeben, die dann eigenständig Änderungen vornehmen können. Wäre auch denkbar eine "Organisation" hier auf Github anzulegen, damit es nicht mehr in meinem persönlichen Profil liegen muss, was das Rechtemanagement auch etwas vereinfacht.

> Weil Github dafür ungeignet ist, und um sich besser auszutauschen zu können als hier.
> Ich weiss, das hier nichts los ist, aber irgendwo muss man ja was machen, sonnst is eine Abspaltung für die Leute die daran noch arbeiten (auch wenn es nicht viel ist) besser.

Wie gesagt, ich stimme dir da zu, dass Github nicht die beste Diskussions-Platform ist und glaube ja auch dass es da bessere Möglichkeiten gibt. Der Ruf nach einem Forum bzw. einer "anderen Platform" erscheint mir allerdings ein bisschen wie ein Cargo-Cult, so nach dem Motto "Wenn wir den Leuten eine (andere) Platform geben, werden sie schon kommen". Das halte ich für Quatsch. Wenn ersthaftes Interesse an diesem Projekt hier bestünde, dann würden sich die Leute hier schon zeigen, denn Github ist nun mal die Platform Nr. 1 für Entwickler und Open Source Projekte weltweit, aber bis auf [ein paar Pull Requests](https://github.com/scheb/open-apexx/pulls?q=is%3Apr+is%3Aclosed) ist ja bisher nichts passiert. So wie ich das sehe seid ihr beide (du und @bigfraggle) wahrscheinlich die einzigen die man als "ernsthaft interessiert" bezeichnen könnte.

Also zusammengefasst, falls von eurer Seite wirklich dieses ernsthafte Interesse besteht kann ich gerne eine "apexx" Organisation auf Github anlegen, das Repository dort hin verschieben und euch der Organisation hinzufügen, so dass ihr alle Rechte habt. Wenn ihr dann neben Github noch irgendeine Platform zum Austausch einrichten wollt könnt ihr das gerne machen. Ich würde mir an eurer Stelle allerdings keine Illusionen machen, dadurch wird das Interesse nicht plötzlich sprunghaft ansteigen.

Ich würde auch gerne mal @bigfraggle dazu hören, du hast dich ja bisher nur mal kurz gemeldet ;)

**Comment by bigfraggle** [comment]
Also ich bin ja schon lange dabei bzw. ehemaliger Kunde, weswegen mir das Projekt durchaus ans Herz gewachsen ist. Ich finde es auch etwas schade, dass Apexx hier so dahinvegetiert, sehe aber im Grunde auch kaum Möglichkeiten, für erneute Popularität zu sorgen und somit die Weiterentwicklung anzukurbeln.

Ich selbst habe für mich ein paar kleinere Änderungen gemacht, zu mehr bin ich jedoch nicht in der Lage, weil ich PHP zwar oft nachvollziehen kann, aber selber deswegen noch lange nicht in der Lage bin, etwas Großes auf die Beine zu stellen.

Da ich das System für ein relativ großes Projekt nutze, werde ich hier auch noch die nächste Zeit am Ball bleiben und hoffen, dass nicht zukünftige PHP-Versionen Probleme bereiten. Wenn ich irgendwo unterstützen kann, dann bin ich dabei. Aber große Impulse in Sachen Entwicklung werde ich fachlich leider nicht leisten können.

In einem neuen Forum sehe ich derzeit auf alle Fälle eher keinen Sinn. Github ist jetzt zwar auch nicht so richtig meins, aber für das bisherige Diskussionsaufkommen reicht die Plattform dann doch allemal.

**Comment by scheb** [comment]
Stichwort neue PHP Version: Da ich selbst noch eine apexx Installation am Laufen habe, werde ich auf jeden Fall auch die Kompatibilität mit PHP8 prüfen und ggfs. die notwendigen Änderungen vornehmen. Also daran wird es erst mal nicht scheitern ;)

**Comment by bigfraggle** [comment]
Oh, das freut mich sehr! :)

**Comment by DOHRMANN-SOFTWARE** [comment]
Na gut, dann missbrauche ich erstmal Github als Forum.
