### ISSUE TITLE
Ist es sinnvoll bei der Deinstalltion eines Modul die Daten komplett zu löschen?

### ISSUE THREAD

**Issue by DOHRMANN-SOFTWARE** [scheb/open-apexx#33]
Bei der Deinstalltion eine Moduls werden ja die Haupttabellen des Moduls gelöscht, aber nicht die Einstellungen des Moduls in der Config-Tabelle.

Ist es sinnvoll, die Einstellungen in der Config-Tabelle bei einer Deinstallation des Moduls zu löschen?

**Comment by scheb** [comment]
Gibt wahrscheinlich Grüde dafür und dagegen. Man kennt das ja von Softwareinstallationen auf dem PC, das man gefragt wird, ob die Einstellungen/Profile mitgelöscht werden sollen. Vielleicht wäre das die richtige Lösung.

**Comment by DOHRMANN-SOFTWARE** [comment]
Also beim deinstallieren wird ja schon auf das Löschen der Daten hingewiesen, und diese Daten sind ja wesentlich wichtiger als die Daten der Einstellungen.
Also soll ich eine Auwahlbox zum bestätigen des löschens der Einstellungen hinzufügen?

**Comment by scheb** [comment]
Fände ich zumindest die sinnvollste Variante.
