### ISSUE TITLE
quicklink-Funktion ändern

### ISSUE THREAD

**Issue by DOHRMANN-SOFTWARE** [scheb/open-apexx#39]
Wäre ist nicht besser, das Aussehen der quicklink-Funktion über das Template zu bestimmen oder generell anzupassen?

An manchen Stellen wird sie genutzt und an manchen nicht.

Man könnte doch das komplette Aussehen im Admin-Center an das Template übergeben, und die benötigen Daten wie die meisten Anderen einfach übergeben.

**Comment by scheb** [comment]
Könnte man sicherlich machen, aber was würde dadurch besser werden?

Ich glaube ich habe das damals in eine PHP Funktion gegossen, da ich den mehr oder weniger identischen Code für deinen Quicklink nicht über alle möglichen Templates duplizieren wollte. So gibt es halt eine zentrale Stelle, wo der Code für einen "Quicklink" generiert wird und der sieht dann garantiert immer gleich aus.
