### ISSUE TITLE
Umlaut-Probleme in PHP 5.6

### ISSUE THREAD

**Issue by niclasd** [scheb/open-apexx#4]
Hey Leute,

nachdem 1&1 mal wieder rumheult und wiedermal eine Umstellung auf eine aktuelle PHP-Version erzwingen möchte, habe ich heute versucht mein altes Apexx für 5.5 bzw 5.6 fit zu machen. Einen Austausch mit den OpenApexx-Dateien hat für PHP 5.5 im Grunde problemlos funktioniert.

Allerdings gibt es ein paar Fehler, wenn man auf 5.6 umstellt:

- Umlaute werden nicht korrekt angezeigt (Lösung: in der lib/cobfig.php UTF8 aktivieren - bei PHP 5.5 ist es genau anders herum, da war die Standardeinstellung False richtig)
- Im Admincenter (Nach UTF8-Aktivierung) wird der Content in den Editoren richtig angezeigt, aber die Umlaute der Oberfläche selbst nicht
- Außerdem werden Umlaute in URLs auch nicht mehr ordnungsgemäß umgeschrieben

Bis auf diese "Kleinigkeiten" ist OpenApexx also offenbar fit für PHP 5.6 - hab es zur Zeit allerdings wieder auf PHP 5.5 umgestellt (und in der Config UTF8 deaktiviert - wie kann das eigentlich je nach PHP-Version zu einem Problem führen?)

Programmier-Erfahrung bei mir leider gleich Null, aber vielleicht helfen meine Anmerkungen ja weiter ;)

**Comment by White4Shadow** [comment]
Das sollte damit zusammenhängen, dass PHP 5.6 soweit ich weiß als default charset UTF-8 benutzt und Umlaute somit anders dargestellt werden (z.B. 'ä' als '&auml'), da in 'Apexx' charset ISO-8859-1 verwendet wird gibt es die Möglichkeit:
1. Apexx komplett auf UTF-8 umzustellen ( meiner Meinung nach höchster Aufwand)
2. Ansonsten sollte eine Änderung in der PHP.ini mit der Zeile ' ;default_charset = "UTF-8" ' ersetzt durch ' default_charset = "ISO-8859-1" ' das problem lösen
3. oder falls die Möglichkeit besteht weiterhin eine Ältere PHP Version benutzen

**Comment by scheb** [comment]
Wer keinen Zugriff auf die php.ini hat (was bei vielen Hostern der Fall ist), kann die Einstellung auch durch einen Eintrag in der `lib/config.php` verändern. Dazu am Ende der Datei vor dem schließenden `?>` folgendes hinzufügen:

```php
ini_set("default_charset", "ISO-8859-1");
```
