### ISSUE TITLE
Frage zur Suche

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#41]
Hallo zusammen,

ich habe eine Frage zur Suche... Und zwar habe ich eine News-Reihe mit dem Namen "Heute vor 10 Jahren", welcher so auch im Newstitel steht. Nun möchte ich mir über die Suche alle News dieser Reihe anzeigen lassen.

1) search.html?q=heute+vor+10+jahren bringt mir alle gesuchten News, dazu kommen aber halt auch welche, die die Wörter ebenfalls enthalten.

2) search.html?q="heute+vor+10+jahren" bringt mir zwar nur die gesuchten News, allerdings nicht vollständig. Von Stand heute 10 Artikeln werden nur 8 aufgeführt.

https://www.xboxaktuell.de

Erste Suche bringt mir zu viele Ergebnisse, zweite zu wenig. Das Verhalten von 1) kann ich nachvollziehen, aber das von 2) nicht. Woran kann das liegen?

**Comment by scheb** [comment]
Ich glaube die Suchfunktion unterstützt eine solche Suche mit Anführungszeichen nicht. Stattdessen sucht sich nach den einzelnen Textfragmenten: `"heute`, `vor`, `10` und `jahren"`

**Comment by bigfraggle** [comment]
Hm, die Frage wäre dann aber, warum Suchmethode 2 überhaupt Ergebnisse ausspuckt...

**Comment by scheb** [comment]
Nunja, hier z.B. https://www.xboxaktuell.de/news,id17695,heute_vor_10_jahren_alan_wunderland.html hast du im News-Text stehen `"Heute vor 10 Jahren"` (exakt so, mit Anführungszeichen) und demenstprechend hast du dann einen Treffer für die Fragmente `"heute` und `jahren"`. Das wird halt nicht bei jeder News der Fall sein.

**Comment by scheb** [comment]
Nachtrag: Im Vergleich dazu, bei dieser News hier https://www.xboxaktuell.de/news,id18080,heute_vor_10_jahren_zwei_irre_killer_dem_trip.html steht zwar auch `"Heute vor 10 Jahren"` im Text, aber du hast einen Link gesetzt. Technisch steht dadurch steht zwischen dem Anführungszeichen und dem `Heute` noch zusätzlicher Content und darum gibt es keinen Treffer für `"Heute`.

Zugegeben, das ist blöd. Die Suchfunktion ist halt ziemlich simpel gestrickt und stößt da an ihre Grenzen.

**Comment by bigfraggle** [comment]
Guter Hinweis!

`"Heute vor 10 Jahren"` taucht zwar in allen gesuchten News auf, in den zwei neuesten, fehlenden hatte ich den Text allerdings mit der Suche verknüpft, also `"<a href="...">Heute vor 10 Jahren</a>"`, um Leser auf ältere Artikel hinzuweisen.

Demzufolge müsste ich also die Anführungsstriche mit verlinken, dann sollte es eigentlich passen - auch wenn das grundsätzlich nicht so "hübsch" wäre...

Oder könnte ich das doch noch eleganter lösen? Ohne eigene Newskategorie?

**Comment by bigfraggle** [comment]
Ups, jetzt warst du schneller...

**Comment by scheb** [comment]
Ja, das hast du richtig erkannt. Wenn du die Anführungszeichen mitverlinkst sollte das eigentlich funktionieren.

Aber gibt's nicht eine "Tagging" Funktionen, die dafür besser geeignet wäre? Alle News der Serie mit einem Tag versehen und dann alle News mit diesem Tag auflisten. Gab's das nicht als Funktion in der News-Übersicht? Bin mir da nicht mehr sicher, zu lange her.

**Comment by bigfraggle** [comment]
Stimmt, Tags gibt es. Habe ich bislang aber nicht wirklich genutzt. Ich schaue mir das mal an. Danke!
