### ISSUE TITLE
Interne, externe und Template-Funktionen

### ISSUE THREAD

**Issue by DOHRMANN-SOFTWARE** [scheb/open-apexx#43]
So wie ich das System verstehe, sind die Datei `admin_system.php` und `tfunctions.php` für Aufrufe im Template zuständig, die Dateien `admin_extend.php` und `functions.php` für Funktionen die man mehrmals und intern nutzt.

Wieso du die Funktionen in der Datei `admin_extend.php` in einer Klasse gekapselt hast verstehe ich nicht, in der Datei `functions.php` sind sie nicht gekappselt. Vielleicht um die genutzten Variablen nur intern in der Datei nutzen zu können, und damit das sie extern nicht überschrieben werden können?

Bei der Funktion `{GALLERIES(GALID)}` ([https://github.com/scheb/open-apexx/blob/master/src/modules/gallery/admin_system.php#L23](https://github.com/scheb/open-apexx/blob/master/src/modules/gallery/admin_system.php#L23)) gibst du die Komplette Auswahlliste aus, aber bei der Funktion `{PRODUCTS(PRODID,ID)}` ([https://github.com/scheb/open-apexx/blob/master/src/modules/products/admin_system.php#L22](https://github.com/scheb/open-apexx/blob/master/src/modules/products/admin_system.php#L22)) nur die Eintrage aus.

Der Vorteil bei `{GALLERIES(GALID)}` ist, das man im Template nichts machen muss, außer den Befehl einzufügen.
Der Nachteil ist, das man der Auswahlliste keinen Namen gebe kann, da der im Code vorgegeben ist.
Bei `{PRODUCTS(PRODID,ID)}` ist es umgkehrt.

Könnte man die Funktionen `products_list` und  `get_product_list` ([https://github.com/scheb/open-apexx/blob/master/src/modules/products/admin_system.php#L22](https://github.com/scheb/open-apexx/blob/master/src/modules/products/admin_system.php#L22)) in einer Funktion packen. Siehe unten.

Ich habe vor, Funktionen aus der Datei `admin_extend.php` die für die optische Ausgabe zuständig sind in die Datei `admin_system.php` zu packen.
Zum Beispiel, die Funktion `get_genre` ist ja auch für die Ausgabe im Template zuständig. In ihr befinden sich HTML-Tags.

Und ich will die Funktionen zusammenzupacken.
Aufrufbeispiel: `product_list($select=0, $ignore=0, $objectid = 'product_list', $entryouput = false)`
So kann man die Objektbezeichnung angeben, die ja auch für Stylesheets wichtig sind, und man kann bestimmen ob man das komplette Objekt oder nur deren Einträge ausgeben will.

Sind die Ideen gut oder schlecht?

**Comment by scheb** [comment]
> Wieso du die Funktionen in der Datei admin_extend.php in einer Klasse gekapselt hast verstehe ich nicht, in der Datei functions.php sind sie nicht gekappselt. Vielleicht um die genutzten Variablen nur intern in der Datei nutzen zu können, und damit das sie extern nicht überschrieben werden können?

Hab mal in den Code reingeschaut. Die Klasse `products_functions` wird ja dann von der `action` Kasse aus der `admin.php` extended. Scheinen mir ein paar Methoden zu sein, die zur `action` Klasse gehören, die ich wohl zwecks besserer Übersicht ausgelagert habe. Die könnten genauso gut auch direkt in der `action` Klasse sein.

> Könnte man die Funktionen products_list und get_product_list (https://github.com/scheb/open-apexx/blob/master/src/modules/products/admin_system.php#L22) in einer Funktion packen. Siehe unten.

Ja, könnte man. Vermutlich ist das ein Überbleibsel. Vermutlich hat die Funktion `products_list` irgendwann mal noch zusätzliche Logik enthalten, die dann aber irgendwann entfernt wurde und somit tut sie nun exakt dasselbe wie die Funktion `get_product_list`.

> Sind die Ideen gut oder schlecht?

Nun, alles was du hier anmerkst sind irgendwelche Inkonsistenzen im Code. Ich sehe auch ein, dass das Inkonsistenzen sind. Sowas hast du allerdings in jedem Projekt und apexx hat da sicher ganz viele von aufgrund seiner Historie und der Tatsache, dass die Software nun schon 15 Jahre alt ist. Es *kann* durchaus sinnvoll sein solche Dinge aufzuräumen.

Ich frage mich allerdings: Wozu das Ganze? Was bringt es uns und vor allem den Nutzer an diesen Inkonsistenzen zu arbeiten? Als du in #32 gefragt hattest "ob es noch Sinn macht etwas beizutragen" dachte ich, da ist jemand der das System wirklich weiterentwickeln kann und möchte. Jemand der neuen "Wert" in der Software schaffen kann. Soetwas wie neue Features, die einem apexx Nutzer wirklich etwas bringen. Stattdessen beschäftigen wir uns größtenteils damit irgendwelche Inkonsistenzen im Code bzw. Verhalten des Systems zu diskutieren, die zugegebenermaßen doof sind, letztendlich aber nicht so schlimm sind, dass man dagegen unbedingt etwas machen müsste. Das wirkt alles nur wie Kosmetik auf mich. Am Ende sieht der Code etwas hübscher aus, aber wesentlich besser oder nützlicher ist das System dadurch nicht geworden.

Ich habe darüber nachgedacht und festgestellt: Das führt alles zu nichts. Insofern mache ich nun das, was aus meiner Sicht das einzig konsequente is, **das Projekt offiziell zu beenden**.

Was heißt das nun für dich? Erst einmal Danke für die Beteiligung und deinen Enthusiasmus, den du für dieses Projekt an den Tag legst. Leider teile ich diesen Enthusiasmus nach all der Zeit nicht mehr. Es steht dir frei einen Fork zu machen und die Weiterentwicklung auf eigene Faust voranzutreiben. Du kannst nach deinen eigenen Regeln weitermachen und all das im Code verändern, was dich stört - was ich aber für unnötig halte. Das ist das schöne an Open Source. Selbst wenn das Hauptprojekt nicht mehr weitergeführt wird kann sich als Person oder Gruppe entscheiden unabhängig weiterzumachen. Ich glaube das ist die beste Lösung für uns beide und für apexx.

**Comment by DOHRMANN-SOFTWARE** [comment]
> Ich frage mich allerdings: Wozu das Ganze? Was bringt es uns und vor allem den Nutzer an diesen Inkonsistenzen zu arbeiten? Als du in #32 gefragt hattest "ob es noch Sinn macht etwas beizutragen" dachte ich, da ist jemand der das System wirklich weiterentwickeln kann und möchte. Jemand der neuen "Wert" in der Software schaffen kann. Soetwas wie neue Features, die einem apexx Nutzer wirklich etwas bringen. Stattdessen beschäftigen wir uns größtenteils damit irgendwelche Inkonsistenzen im Code bzw. Verhalten des Systems zu diskutieren, die zugegebenermaßen doof sind, letztendlich aber nicht so schlimm sind, dass man dagegen unbedingt etwas machen müsste. Das wirkt alles nur wie Kosmetik auf mich. Am Ende sieht der Code etwas hübscher aus, aber wesentlich besser oder nützlicher ist das System dadurch nicht geworden.

In erster Linie mache ich das ja für mich. Im Grunde, ist ja APEXX so wie es ist ja gut. Aber ich brauche manche Sachen, die halt nicht vorhanden sind. Na gut, das sind eigendlich nur Datenfelder, aber wenn ich schon dabei bin was zu ändern, kann ich auch gleich mehr Struktur in das ganze bringen, so ist die Entwicklung und Übersicht für mich einfacher.
Aber es ist auch wichtig, für weitere Entwicklungen.

Das mit dem neueren "Wert" ist so eine Sache. Dazu müssten die Nutzer ja kommen und anfragen bzw. das Entwickler Ideen dazu haben.
Ich versuche halt die Sachen die ich brauche einzufügen, und wenn es fertig ist zu veröffentlichen.
Ich bin halt leider nur ein Nutzer, und mache nichts anderes als Flickschusterei.

Na gut, dann muss ich doch eine Abspaltng machen.
Dazu hätte ich noch ein paar Fragen.
1. Ich würde es dann gerne APIXX nennen. Ist das in Ordnung?
2. Ich würde gerne im Grund das Logo übernehmen, aber in Großbuchstaben, und ohne 'cms & Portalsystem'. Ist das in Ordnung?
3. Wie gebe ich dich und den Ursprung richtig an?

**Comment by scheb** [comment]
> Ich würde es dann gerne APIXX nennen. Ist das in Ordnung?

Spricht nichts dagegen, das geforkte Projekt unter anderem Namen zu führen. Ist sogar üblich das umzubenennen um Verwechslungen mit dem "Original" vorzubeugen.

> Ich würde gerne im Grund das Logo übernehmen, aber in Großbuchstaben, und ohne 'cms & Portalsystem'. Ist das in Ordnung?

Nein, das möchte ich nicht.

> Wie gebe ich dich und den Ursprung richtig an?

Wenn du einen Fork hier auf Github machst dann ist das Repository automatisch mit dem Ursprungsrepository (diesem hier) verknüpft. Ansonsten reicht eine Erwähnung in der Readme.

Ganz wichtig: Die Lizenz muss erhalten bleiben und darf nicht verändert werden. Eine Übersicht zu den Lizenzbedingungen gibt es hier: https://github.com/scheb/open-apexx/blob/master/LICENSE

**Comment by bigfraggle** [comment]
Kurze Anmerkung: Im Grunde fände ich es sehr schade, wenn man ein mittlerweile eh schon kleines Projekt durch einen Fork jetzt noch verkleinert. In Zukunft kümmert sich dann einer um Apexx, ein anderer um Apixx. Das macht einfach wenig Sinn.

**Comment by DOHRMANN-SOFTWARE** [comment]
Ich finde es auch sehr schade!
APEXX ist ist in der Bedienung schön klein und einfach.

Und Christian hat ein tolles CMS gemacht.
Na gut ich kenne nur noch Joomla und ein spezielles CMS.
Aber mir gefällt die Einfachheit. eine modernes Aussehen und Schnick-Schnack, kann man ja über die Templates machen.

Aber es ist wie es ist.

**Comment by bigfraggle** [comment]
Vielleicht solltest du das Projekt dann einfach für dich lokal weiterentwickeln. Ein Fork bei Github macht so einfach keinen Sinn.

**Comment by bigfraggle** [comment]
@scheb: Das komplette Herunterfahren empfinde ich jetzt ehrlich gesagt auch irgendwie als Kurzschlussreaktion. Mag sein, dass eine Weiterentwicklung mit der Basis kaum möglich ist, aber so nimmt man den letzten Verbliebenen dann doch die Möglichkeit, sich mal zur Not auszutauschen - und sei es bald wegen PHP8. Ist ja nicht so, dass ein offenes Repository für dich Verpflichtungen in Sachen Support oder Aufwand bedeuten. Schade...

**Comment by scheb** [comment]
Also ich sehe das so: Ich mache damit nur etwas offiziell, dass schon seit Langem ohnehin der Fall ist. Es gab nun mehrere Anläufe (die ersten im alten Stylemotion Forum , dann mehrmals hier) das Projekt weiterzuentwickeln, allerdings fehlte jedes Mal - auch dieses Mal - die Vision das Projekt voranzubringen. Stattdessen passiert nur Kosmetik und Flickwerk.

Ich denke es ist auch fair gegenüber den verbleibenden Nutzern jetzt klar zu sagen, dass es hier (in diesem Repository) keine Weiterentwicklung stattfinden wird, anstatt sich an irgendwelche falschen Hoffnungen zu klammern.

Wie ich bereits oben sagte, es steht jedem frei das Repository zu forken und nach den eigenen Regeln weiterzuentwickeln. Ich finde auch nicht, dass ein Fork schlecht für die "Community" ist. Ein Fork der weiterentwickelt wird ist besser als ein Projekt, das sich gar nicht mehr bewegt. Ich hätte auch kein Problem damit einen Fork in der Readme zu verlinken, um dem mehr Sichtbarkeit zu geben.

Und ich möchte auch nochmal klarstellen, was es bedeutet, dass das Projekt nun "beendet" ist, weil das offenbar nicht ganz klar ist:

1) Das Repository hier wird weiterhin verfügbar bleiben, die Software verschwindet nicht einfach.
2) Es wird weiterhin möglich sein Issues zu erstellen. Es sollte nur klar sein, dass man nicht unbedingt eine Reaktion erwarten und keine Änderungen mehr umgesetzt werden. Damit ist ein Austausch natürlich weiterhin möglich.
3) Es wird keine Weiterentwicklung der Software geben (im Sinne von: neue Features, Bugfixes). Das heißt aber nicht, dass sich hier gar nichts mehr tut. Dieses Repository ist heutzutage meine "Master-Kopie" von Apexx. Ich werde mir aus eigenem Interesse die PHP8 Version vornehmen und sollten dafür irgendwelche Anpassungen notwendig und durchführbar sein, werden diese auch hier im Repository auftauchen. Es gibt nur keine Garantie, dass sich hier etwas tut (nun, die gab es auch vorher schon nicht, insofern hat sich nichts geändert).

**Comment by bigfraggle** [comment]
Danke für die "Klarstellung".

Die Tatsache, dass hier alles automatisch geschlossen wurde, und der Statushinweis, dass das Repository keine Issues und Pull Requests mehr annimmt, klangen zusammen anders.

Ich denke, die Chance Apexx am Leben zu erhalten, wurde damals schon in der Stylemotion Community vertan, als es noch genügend Nutzer gab. Ich hätte mich dem Ganzen sogar gerne angenommen, aber halt auch jemanden mit Programmiererfahrung an meiner Seite gebraucht. Tja...
