### ISSUE TITLE
{php} funktioniert nicht mehr // PHP 5.5

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#5]
Hallo zusammen,

vielleicht ließt ja hier jemand mit...

Seit Nutzung von PHP 5.5 und Update auf die 1.7.2 funktioniert die Einbindung von PHP-Code mittels {php} nicht mehr.

Testweise habe ich eine neue Subdomain eingerichtet und eine komplett saubere, neue Installation mit keinerlei Änderungen durchgeführt.

Ich weiß gar nicht, ob es bislang einen Unterschied gemacht hat, ob man externen Code mit {php} oder {PHP} eingebunden hat. Jetzt will es das System mal so, mal so. In manchen Templates muss ich es klein schreiben, in anderen groß. Und manchmal wird der Code gar nicht ausgeführt.

Dann bekomme ich solch eine Fehlermeldung:

```
"Parse error: syntax error, unexpected 'date' (T_STRING) in /templates%1%default%1%design_default%2%html1452175641.php on line 213"
```

In diesem konkreten Fall habe ich in der original design_default.html (als einzige Änderung) spaßeshalber mal ein `{php}echo date("Y"){/php}` in den Copyright-Footer gepackt. Schreibe ich das `{php}` groß, gibt es keine Fehlermeldung, dafür gibt mir das System auf der Seite lediglich `echo date("Y"){/PHP}` aus.

Wäre klasse, wenn jemand eine Idee hätte.

Danke
Marc

**Comment by scheb** [comment]
Funktioniert bei mir unter PHP 5.6. Ich glaube eher es liegt an dem fehlenden `;` am Ende. Probiere es mal so:

```
{php} echo date("Y"); {/php}
```

**Comment by bigfraggle** [comment]
Stundenlang habe ich mich jetzt damit beschäftigt und war kurz vor einem Nervenzusammenbruch. Und dann ist es so eine Kleinigkeit...

Es lag am Semikolon UND an den Leerzeichen nach bzw. vor den php-Tags. Uff.

Ich danke dir! :)
