### ISSUE TITLE
Cronjob Image

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#7]
Keine Ahnung, ob das früher auch schon so war oder ob das an der "aktuellen" Version (Neuinstallation) bzw. meinem PHP-Update auf die 5.5 liegen könnte...

Auf jeder Seite wird eine 1px große Grafikdatei in den Quellcode gepackt, mit der die Cronjobs gesteuert werden. Bei meinen Stichproben wurde diese von den Browsern aber nicht gefunden. Bei Firefox, IE und Edge ist das egal, die zeigen sie einfach nicht an. Chrome und darauf basierende Android-Browser spucken an der Stelle allerdings eine Fehlergrafik aus. Die ist zwar auch nur 1px zzgl. Rahmen groß, fällt aber je nach Hintergrundfarbe auf.

Erzeugt wird die Grafik in lib/class.templates.public in den Zeilen 110 bis 114.
Als Workaround könnte man da jetzt ein "visibility: hidden" zufügen. Bin mir aber nicht so sicher, ob es da noch ein tiefer greifendes Problem geben könnte.

Grüße
Marc

**Comment by scheb** [comment]
Kann ich bei mir nicht reproduzieren. Hast du eine Beispiel-URL wo man das Problem sehen kann?

**Comment by bigfraggle** [comment]
Z.B. hier: http://www.xboxaktuell.de
Habe auch noch eine zweite Seite, die ist derzeit aber nicht öffentlich zugänglich. Bei Bedarf kann ich Link und Zugangsdaten gerne privat mitteilen. Dort ist das Problem ebenfalls vorhanden.

In beiden Fällen wurde eine saubere Installation vorgenommen, Restbestände früherer Versionen gibt es nicht.

**Comment by scheb** [comment]
Du solltest mal genauer untersuchen, wie es zu diesem Fehler kommt. Ich vermute hier eher ein Problem mit der Server-Konfiguration als eines mit apexx.
```
Verbindung konnte nicht hergestellt werden!
MySQL meldet: No such file or directory
```
http://www.xboxaktuell.de/lib/cronjob/cron.php?hash=123

**Comment by bigfraggle** [comment]
Ok, den Hinweis hatte ich schon mal gelesen, konnte mir da aber keinen großen Reim drauf machen...

ABER. Als ich mit der PHP 5.5 auf mysqli umsteigen musste, konnte ich anfangs keine Verbindung zur DB aufbauen. Der 1&1-Support half mir dann mit einem Befehl für die php.ini weiter:

> mysql.default_socket = /tmp/mysql5.sock
pdo_mysql.default_socket = /tmp/mysql5.sock
mysqli.default_socket = /tmp/mysql5.sock

Habe dies jetzt nicht nur ins Haupt- und Adminverzeichnis gepackt, sondern auch in den lib-Ordner. Damit scheint die Grafik nun geladen werden zu  können.

Ich beobachte das mal, und schließe hier dann ggf. die Tage.
Vielleicht ist damit ja auch die Twitter-Sache erledigt.

Vielleicht für alle interessant, die einen Managed Server bei dem Verein haben...
