### ISSUE TITLE
Modifikatoren für Variablen funktionieren nicht mehr

### ISSUE THREAD

**Issue by bigfraggle** [scheb/open-apexx#8]
Hallo,

seit meinem PHP-Update auf die 5.5 und der Nutzung der 1.7.2 gibt's ein Problem mit den Textfeldern "Positives" und "Negatives" bei den Tests.

Bislang galt immer: eine Zeile im Backend entspricht eine Zeile im eigentlichen Test. Jetzt werden die Zeilen plötzlich ignoriert und alles direkt hintereinander ausgegeben. Da für diese Pros und Cons kein CKEditor vorgesehen ist, muss man immer manuell HTML-Breaks setzen.

Edit: Das "breaks" aus {POSITIVE|breaks} bzw. {NEGATIVE|breaks} scheint nicht mehr zu funktionieren.

Grüße
Marc

**Comment by bigfraggle** [comment]
Ok, im Template kann ich das wieder korrigieren...

`{php} echo nl2br( $this->parsevars['POSITIVE']); {/php}`
bzw.
`{php} echo nl2br( $this->parsevars['NEGATIVE']); {/php}`

Scheint aber mit {VARIABLE|breaks} ein grundsätzliches Problem zu geben. Wie ich in der class.tengine.compiler.php gesehen habe, versteckt sich hinter "breaks" ja eben diese nl2br-Funktion. Warum wird die dann nicht (mehr) ausgeführt?

**Comment by bigfraggle** [comment]
Ok, wir haben hier anscheinend ein grundlegendes Problem...

{VARIABLE|replace}
{VARIABLE|breaks}
{VARIABLE|notags}
{VARIABLE|upper}
{VARIABLE|lower}

Funktionieren alle nicht mehr!

**Comment by scheb** [comment]
Commit 0c57b72032167ddc9492e7efaf0f45519dff7915 enthält den Bugfix.
